import 'server-only';

/**
 * Guardrails — Part 7, and Appendix A step 11 items 9–12.
 *
 * Three jobs:
 *   · bound the input, so a paste bomb cannot become a token bill
 *   · neutralise the obvious prompt-injection shapes
 *   · mask personal data before it leaves the machine
 *
 * None of this is a security boundary on its own. Prompt injection is
 * not solved by filtering, so the real defence is architectural: this
 * layer has no tools, no network access beyond the model, and no
 * authority to act. Its output is text rendered into a page and
 * labelled as generated, nothing more.
 */

const MAX_INPUT_CHARS = 12_000;

/** Instruction-override shapes that appear in almost every injection attempt. */
const INJECTION_PATTERNS: RegExp[] = [
  /ignore\s+(all\s+)?(previous|prior|above)\s+instructions/gi,
  /disregard\s+(all\s+)?(previous|prior|the)\s+(instructions|rules|system)/gi,
  /you\s+are\s+now\s+(a|an)\s+/gi,
  /\bsystem\s*(prompt|message)\s*[:=]/gi,
  /<\|?(im_start|im_end|system|assistant)\|?>/gi,
  /reveal\s+(your|the)\s+(system\s+)?(prompt|instructions)/gi,
];

/** Patterns worth masking on the way out of the user's browser. */
const PII_PATTERNS: { pattern: RegExp; replacement: string }[] = [
  { pattern: /[\w.+-]+@[\w-]+\.[\w.-]+/g, replacement: '[email]' },
  { pattern: /\b(?:\+?\d{1,3}[\s-]?)?(?:\(\d{2,4}\)[\s-]?)?\d{3,4}[\s-]?\d{3,4}[\s-]?\d{0,4}\b/g, replacement: '[phone]' },
  { pattern: /\b(?:\d[ -]*?){13,19}\b/g, replacement: '[card]' },
];

export function guardInput(input: string): string {
  let text = input.slice(0, MAX_INPUT_CHARS);

  for (const pattern of INJECTION_PATTERNS) {
    text = text.replace(pattern, '[removed]');
  }

  // Wrap the untrusted span so the model has an unambiguous boundary
  // between our instructions and the user's text.
  return `<user_input>\n${text}\n</user_input>`;
}

export function maskPii(input: string): string {
  let text = input;
  for (const { pattern, replacement } of PII_PATTERNS) {
    text = text.replace(pattern, replacement);
  }
  return text;
}

/**
 * Output hygiene. The result is rendered as text, never as HTML, so
 * this strips the constructs that would matter if that ever changed.
 */
export function guardOutput(output: string): string {
  return output
    .replace(/<script[\s\S]*?<\/script>/gi, '')
    .replace(/<iframe[\s\S]*?<\/iframe>/gi, '')
    .replace(/\bjavascript:/gi, '')
    .replace(/\bdata:text\/html/gi, '')
    .trim();
}

/**
 * Schema check for features that ask a model for structured output.
 * A model that returns prose where JSON was expected is a normal
 * event, not an exception — treat it as a validation failure and fall
 * back, never as a crash.
 */
export function parseStructured<T>(raw: string, isValid: (value: unknown) => value is T): T | null {
  const fenced = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  const candidate = (fenced?.[1] ?? raw).trim();

  try {
    const parsed: unknown = JSON.parse(candidate);
    return isValid(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/** Every AI surface must carry this. Non-negotiable — step 11 item 13. */
export const AI_DISCLOSURE =
  'Generated by an AI model. Check anything you are going to rely on.';
